---
title: "Untitled"
author: "Mason Putt"
date: "2/13/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
### Install these packages before continuing if necessary:

# install.packages("tidyverse")
# install.packages("splitstackshape")
# install.packages("stringi")
```

```{r}
### Load data
EvLab <- read.csv("~/Desktop/ECON 2841 - Capstone/Data/Eviction Lab/cities.csv")
CHAS8 <- read.csv("~/Desktop/ECON 2841 - Capstone/Data/CHAS/Table8.csv", header=TRUE)
# CHAS14A <- read.csv("~/Desktop/ECON 2841 - Capstone/Data/CHAS/Table14A.csv", header=TRUE)
# CHAS14B <- read.csv("~/Desktop/ECON 2841 - Capstone/Data/CHAS/Table14B.csv", header=TRUE)
# CHAS15A <- read.csv("~/Desktop/ECON 2841 - Capstone/Data/CHAS/Table15A.csv", header=TRUE)
# CHAS15B <- read.csv("~/Desktop/ECON 2841 - Capstone/Data/CHAS/Table15B.csv", header=TRUE)
# CHAS15C <- read.csv("~/Desktop/ECON 2841 - Capstone/Data/CHAS/Table15C.csv", header=TRUE)

### Load packages required for cleaning
library(tidyverse)
library(splitstackshape)
library(stringi)
library(plyr)

# Fixing problem with character "ñ"
CHAS8$name <- as.character(CHAS8$name)
CHAS8$name <- str_replace(CHAS8$name, "\xf1", "ñ")
# Splitting the "name" column into county, city, state
CHAS8 <- cSplit(CHAS8,as.character("name"), sep = ", ")
CHAS8$type <- word(CHAS8$name_2, -1)
CHAS8$city <- gsub("\\s*\\w*$", "", CHAS8$name_2)
CHAS8$county <- str_remove(CHAS8$name_1, "\\(part\\)")
CHAS8$city_state <- paste(CHAS8$city, CHAS8$name_3 ,sep="_")

EvLab$city_state <- paste(EvLab$name, EvLab$parent.location ,sep="_")

# Keeping and renaming only relevant metrics
CHAS8 <- select(CHAS8, city, type, county, state=name_3, city_state, T8_est1, T8_est2, T8_est3, T8_est16, T8_est29, T8_est42, T8_est55, T8_est68, T8_est69, T8_est82, T8_est95, T8_est108, T8_est121) %>%
  filter(T8_est1!=0)

# Matching the data
EvLab$match <- EvLab$city_state %in% CHAS8$city_state
EvLab <- filter(EvLab, match==TRUE)
CHAS8$match <- CHAS8$city_state %in% EvLab$city_state
CHAS8 <- filter(CHAS8, match==TRUE)

fulldata <- merge(EvLab, CHAS8, by="city_state")
```